# Generated by Django 3.2.4 on 2021-07-09 19:14

from django.db import migrations, models
import post.my_models.custom_user


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=post.my_models.custom_user.CustomUser.image_path),
        ),
    ]
