# Generated by Django 3.2.4 on 2021-06-29 13:54

from django.db import migrations, models
import post.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_number_of_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-number_of_likes'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_large',
            field=models.ImageField(upload_to=post.models.post.Post.image_path),
        ),
    ]
