# Generated by Django 3.2.4 on 2021-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210629_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('not_verified', 'Not verified'), ('rejected', 'Rejected')], default='not_verified', max_length=255),
        ),
    ]
