# Generated by Django 3.2.4 on 2021-07-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_large',
            new_name='img',
        ),
    ]
