# Generated by Django 3.2.4 on 2021-06-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='like',
            table='Like',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
